version: "3"
services:

  init-guacamole-db:
    image: guacamole/guacamole:latest
    command: ["/bin/sh", "-c", "test -e /init/initdb.sql && echo 'init file already exists' || /opt/guacamole/bin/initdb.sh --postgres > /init/initdb.sql" ]
    volumes:
      - dbinit:/init    

  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - dbinit:/docker-entrypoint-initdb.d        
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-guacdb}
      POSTGRES_PASSWORD: 
    depends_on:
      - init-guacamole-db
    network_mode: host

  guacd:
    image: guacamole/guacd:latest
    restart: unless-stopped
    network_mode: host

  guac:
    image: guacamole/guacamole:latest
    restart: unless-stopped
#     ports:
#       - "80:8080"
    environment:
      GUACD_HOSTNAME: "127.0.0.1"
      POSTGRES_HOSTNAME: "127.0.0.1"
      POSTGRES_DATABASE: ${POSTGRES_USER:-guacdb}
      POSTGRES_USER: ${POSTGRES_USER:-guacdb}
      POSTGRES_PASSWORD:
    depends_on:
      - postgres
      - guacd
    network_mode: host
  
  openssh-server:
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        - SSH_USERNAME=$SSH_USERNAME
        - SSH_PASSWORD=$SSH_PASSWORD
        - ZIP_PASS=$ZIP_PASS
    container_name: openssh-server
    ports:
      - '2222:22'
    restart: unless-stopped
    networks:
      - net
    volumes:  
      - ~/YaraShare:/YaraShare

volumes:
  dbinit:
    driver: local
  dbdata:
    driver: local

networks: 
  net:
    external: true
