client: 'fileshot-sample-exercise-4'
conn:
  server: 'strelka_frontend_1:57314'
  #cert: './strelka.crt'
  timeout:
    dial: 5s
    file: 5m
throughput:
  concurrency: 8
  chunk: 98304
  delay: 1s
files:
  patterns:
    - './samples/*.docx'
  delete: false
  gatekeeper: false
response:
  log: './exercise-4.log'
